/**
 *
 */
package io.github.belingueres.dinuk.jdbc;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 */
public class DinukConnection implements Connection {

    private static final Logger log = LoggerFactory.getLogger(DinukConnection.class);

    private final Connection delegate;
	private final Configuration configuration;

    public DinukConnection(Configuration config, Connection delegate) {
		this.configuration = config;
        this.delegate = delegate;
    }

    public Connection getDelegateConnection() {
        return delegate;
    }

    // -------------------------------------------------------
    // Core interception points
    // -------------------------------------------------------

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return prepareRewritten(sql, delegate::prepareStatement);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
            throws SQLException {
        return prepareRewritten(sql, s -> delegate.prepareStatement(s, resultSetType, resultSetConcurrency));
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
            int resultSetHoldability) throws SQLException {
        return prepareRewritten(sql, s -> delegate.prepareStatement(s, resultSetType, resultSetConcurrency, resultSetHoldability));
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return prepareRewritten(sql, s -> delegate.prepareStatement(s, autoGeneratedKeys));
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return prepareRewritten(sql, s -> delegate.prepareStatement(s, columnIndexes));
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return prepareRewritten(sql, s -> delegate.prepareStatement(s, columnNames));
    }

    private PreparedStatement prepareRewritten(String sql, PrepareStatementFactory delegatePreparer)
            throws SQLException {
        SQLStatementTranslator translator = configuration.resolve(sql);
        if (translator == null) {
            log.trace("connection hash: {}, executing SQL: {}", this.hashCode(), sql);
            return delegatePreparer.prepare(sql);
        }
        log.debug("connection hash: {}, SQL: {}", this.hashCode(), sql);
        return new DinukPreparedStatement(configuration, this, translator, delegatePreparer::prepare);
    }

    @Override
    public Statement createStatement() throws SQLException {
        // For plain Statement, wrap so executeXxx() calls also get rewritten
        return new DinukDelegateStatement<Statement>(configuration, this, delegate.createStatement());
    }

	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
		return new DinukDelegateStatement<Statement>(configuration, this, delegate.createStatement(resultSetType, resultSetConcurrency));
	}

	@Override
	public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
			throws SQLException {
		return new DinukDelegateStatement<Statement>(configuration, this,
				delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability));
	}

    // -------------------------------------------------------
    // Boilerplate delegation for all other Connection methods
    // -------------------------------------------------------

    @Override public void     close()               throws SQLException { delegate.close(); }
    @Override public boolean  isClosed()            throws SQLException { return delegate.isClosed(); }
    @Override public void     commit()              throws SQLException { delegate.commit(); }
    @Override public void     rollback()            throws SQLException { delegate.rollback(); }
    @Override public void     setAutoCommit(boolean b) throws SQLException { delegate.setAutoCommit(b); }
    @Override public boolean  getAutoCommit()       throws SQLException { return delegate.getAutoCommit(); }
    @Override public DatabaseMetaData getMetaData() throws SQLException { return delegate.getMetaData(); }
    @Override public void     setReadOnly(boolean b)  throws SQLException { delegate.setReadOnly(b); }
    @Override public boolean  isReadOnly()          throws SQLException { return delegate.isReadOnly(); }
    @Override public void     setCatalog(String c)  throws SQLException { delegate.setCatalog(c); }
    @Override public String   getCatalog()          throws SQLException { return delegate.getCatalog(); }
    @Override public void     setTransactionIsolation(int l) throws SQLException { delegate.setTransactionIsolation(l); }
    @Override public int      getTransactionIsolation() throws SQLException { return delegate.getTransactionIsolation(); }
    @Override public SQLWarning getWarnings()       throws SQLException { return delegate.getWarnings(); }
    @Override public void     clearWarnings()       throws SQLException { delegate.clearWarnings(); }
    @Override public CallableStatement prepareCall(String sql) throws SQLException { return delegate.prepareCall(sql); }
    @Override public CallableStatement prepareCall(String sql, int t, int c) throws SQLException { return delegate.prepareCall(sql, t, c); }
    @Override public CallableStatement prepareCall(String sql, int t, int c, int h) throws SQLException { return delegate.prepareCall(sql, t, c, h); }
    @Override public String   nativeSQL(String sql) throws SQLException { return delegate.nativeSQL(sql); }
    @Override public Map<String, Class<?>> getTypeMap() throws SQLException { return delegate.getTypeMap(); }
    @Override public void     setTypeMap(Map<String, Class<?>> m) throws SQLException { delegate.setTypeMap(m); }
    @Override public void     setHoldability(int h) throws SQLException { delegate.setHoldability(h); }
    @Override public int      getHoldability()      throws SQLException { return delegate.getHoldability(); }
    @Override public Savepoint setSavepoint()       throws SQLException { return delegate.setSavepoint(); }
    @Override public Savepoint setSavepoint(String n) throws SQLException { return delegate.setSavepoint(n); }
    @Override public void     rollback(Savepoint s) throws SQLException { delegate.rollback(s); }
    @Override public void     releaseSavepoint(Savepoint s) throws SQLException { delegate.releaseSavepoint(s); }
    @Override public Clob     createClob()          throws SQLException { return delegate.createClob(); }
    @Override public Blob     createBlob()          throws SQLException { return delegate.createBlob(); }
    @Override public NClob    createNClob()         throws SQLException { return delegate.createNClob(); }
    @Override public SQLXML   createSQLXML()        throws SQLException { return delegate.createSQLXML(); }
    @Override public boolean  isValid(int timeout)  throws SQLException { return delegate.isValid(timeout); }
    @Override public void     setClientInfo(String n, String v) throws SQLClientInfoException { delegate.setClientInfo(n, v); }
    @Override public void     setClientInfo(Properties p) throws SQLClientInfoException { delegate.setClientInfo(p); }
    @Override public String   getClientInfo(String n) throws SQLException { return delegate.getClientInfo(n); }
    @Override public Properties getClientInfo()     throws SQLException { return delegate.getClientInfo(); }
    @Override public Array    createArrayOf(String t, Object[] e) throws SQLException { return delegate.createArrayOf(t, e); }
    @Override public Struct   createStruct(String t, Object[] a) throws SQLException { return delegate.createStruct(t, a); }
    @Override public void     setSchema(String s)   throws SQLException { delegate.setSchema(s); }
    @Override public String   getSchema()           throws SQLException { return delegate.getSchema(); }
    @Override public void     abort(Executor e)     throws SQLException { delegate.abort(e); }
    @Override public void     setNetworkTimeout(Executor e, int ms) throws SQLException { delegate.setNetworkTimeout(e, ms); }
    @Override public int      getNetworkTimeout()   throws SQLException { return delegate.getNetworkTimeout(); }
    @Override public <T> T    unwrap(Class<T> iface) throws SQLException { return delegate.unwrap(iface); }
    @Override public boolean  isWrapperFor(Class<?> iface) throws SQLException { return delegate.isWrapperFor(iface); }
}